/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcestudiantes.view;


import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author UIS
 */
public class VMenuClases extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VMenuClases.class.getName());

    /**
     * Creates new form MenuClases
     */
    public VMenuClases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrinc = new javax.swing.JPanel();
        btnMatruculaEst = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnProfesores = new javax.swing.JButton();
        btnEstudiantes = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMatruculaEst.setBackground(new java.awt.Color(0, 0, 0));
        btnMatruculaEst.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnMatruculaEst.setForeground(new java.awt.Color(51, 255, 102));
        btnMatruculaEst.setText("Matricular Estudiantes");
        btnMatruculaEst.addActionListener(this::btnMatruculaEstActionPerformed);

        btnAsignar.setBackground(new java.awt.Color(0, 0, 0));
        btnAsignar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnAsignar.setForeground(new java.awt.Color(51, 255, 102));
        btnAsignar.setText("Asignar Profesor");
        btnAsignar.addActionListener(this::btnAsignarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText(" Sistema Academico");

        btnProfesores.setBackground(new java.awt.Color(0, 0, 0));
        btnProfesores.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnProfesores.setForeground(new java.awt.Color(51, 255, 102));
        btnProfesores.setText("Profesores");
        btnProfesores.addActionListener(this::btnProfesoresActionPerformed);

        btnEstudiantes.setBackground(new java.awt.Color(0, 0, 0));
        btnEstudiantes.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEstudiantes.setForeground(new java.awt.Color(51, 255, 102));
        btnEstudiantes.setText("Estudiantes");
        btnEstudiantes.addActionListener(this::btnEstudiantesActionPerformed);

        btnMaterias.setBackground(new java.awt.Color(0, 0, 0));
        btnMaterias.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnMaterias.setForeground(new java.awt.Color(51, 255, 102));
        btnMaterias.setText("Materias");
        btnMaterias.addActionListener(this::btnMateriasActionPerformed);

        btnSalida.setBackground(new java.awt.Color(0, 0, 0));
        btnSalida.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(51, 255, 102));
        btnSalida.setText("Salir");
        btnSalida.addActionListener(this::btnSalidaActionPerformed);

        jLabel2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione la accion que desea realizar");

        javax.swing.GroupLayout JPanelPrincLayout = new javax.swing.GroupLayout(JPanelPrinc);
        JPanelPrinc.setLayout(JPanelPrincLayout);
        JPanelPrincLayout.setHorizontalGroup(
            JPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincLayout.createSequentialGroup()
                        .addGroup(JPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincLayout.createSequentialGroup()
                                .addComponent(btnProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincLayout.createSequentialGroup()
                                .addComponent(btnAsignar)
                                .addGap(99, 99, 99)
                                .addComponent(btnMatruculaEst, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincLayout.createSequentialGroup()
                        .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
            .addGroup(JPanelPrincLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
        );
        JPanelPrincLayout.setVerticalGroup(
            JPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(JPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanelPrincLayout.createSequentialGroup()
                        .addGroup(JPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(JPanelPrincLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMatruculaEst, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatruculaEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatruculaEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatruculaEstActionPerformed

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        ScreenManager.abrirProfesores();
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        ScreenManager.abrirMaterias();
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        ScreenManager.abrirEstudiantes();
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VMenuClases().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelPrinc;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnEstudiantes;
    private javax.swing.JButton btnMaterias;
    private javax.swing.JButton btnMatruculaEst;
    private javax.swing.JButton btnProfesores;
    private javax.swing.JButton btnSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
